services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  #prod:
  #build:
  #context: .
  #dockerfile: Dockerfile.prod
  #ports:
  #- '4000:4000'
