import './globals.css'
import { Inter } from 'next/font/google'
import { Title } from '@/components/Title'
import { CartButton } from '@/components/CartButton'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Analytics } from '@vercel/analytics/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Supermarket Price Comparator',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='flex flex-col min-h-screen'>
				<main className='flex-grow px-4 '>
					<Title />
					{children}
					<SpeedInsights />
					<Analytics />
				</main>
				<footer className='text-white text-center mb-20'>
					Última actualización de productos: 12/06/2024
				</footer>
				<CartButton />
			</body>
		</html>
	)
}
