name: CI Pipeline

on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Packages
        uses: npm install

      - name: Bundle
        uses: npm run build
